name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install fastapi
          pip install uvicorn
          pip install dash
          pip install dash-bootstrap-components
          pip install pandas
          pip install httpx
          pip install sqlalchemy
          pip install alembic
          pip install passlib[bcrypt]
          pip install python-dotenv    
          pip install selenium
          pip install requests
          pip install pytest
          pip install pytest-cov
          pip install pytest-asyncio
          pip install pylint
          pip install black
      - name: Run tests
        working-directory: AGRO_CLIMA_APP
        run: |
          python -m pytest --cov=app ./tests/


