name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install chromedriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          echo "Chromedriver installed at: $(which chromedriver || true)"
          if ! command -v chromedriver >/dev/null 2>&1; then
            if [ -f /usr/lib/chromium-browser/chromedriver ]; then
              sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
            elif [ -f /usr/lib/chromium/chromedriver ]; then
              sudo ln -sf /usr/lib/chromium/chromedriver /usr/bin/chromedriver
            fi
          fi

      - name: Install dependencies
        working-directory: AGRO_CLIMA_APP/AGRO_CLIMA_APP
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI backend
        working-directory: AGRO_CLIMA_APP/AGRO_CLIMA_APP
        run: |
          nohup python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        env:
          PYTHONPATH: .

      - name: Start frontend
        working-directory: AGRO_CLIMA_APP/AGRO_CLIMA_APP
        run: |
          nohup python frontend.py &
        env:
          PYTHONPATH: .

      - name: Wait for servers to start
        run: sleep 05
        


      - name: Check chromedriver permissions
        run: |
          ls -l /usr/bin/chromedriver
          which chromedriver
          
      - name: Run tests
        working-directory: AGRO_CLIMA_APP/AGRO_CLIMA_APP
        run: |
          python -m pytest --cov=app tests/
