name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./AGRO_CLIMA_APP
        run: |
          pip install --upgrade pip

      - name: Run tests in AGRO_CLIMA_APP
        working-directory: ./AGRO_CLIMA_APP
        run: |
          python -m pytest --cov=app tests/

